    # ============================================================
    # LOCAL PROFILE
    # How to run: mvn spring-boot:run (local is default profile)
    # ============================================================

    # =========================
    # DATASOURCE (PostgreSQL)
    # =========================
    spring.datasource.url=jdbc:postgresql://localhost:5433/performancedb
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=root
    spring.datasource.password=root

    # HikariCP settings
    spring.datasource.hikari.maximum-pool-size=5
    spring.datasource.hikari.minimum-idle=2
    spring.datasource.hikari.connection-timeout=30000
    spring.datasource.hikari.pool-name=LocalPool

    # =========================
    # JPA SETTINGS
    # =========================
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.show-sql=true

    # =========================
    # FLYWAY SETTINGS
    # =========================
    spring.flyway.enabled=true
    spring.flyway.locations=classpath:db/migration

    # =========================
    # REDIS SETTINGS
    # =========================
    spring.data.redis.host=localhost
    spring.data.redis.port=6379

    # =========================
    # LOGGING
    # =========================
    logging.level.com.hr.performancetracker=DEBUG
    logging.level.org.hibernate.SQL=DEBUG
    logging.level.org.hibernate.orm.jdbc.bind=TRACE
    logging.level.org.flywaydb=INFO